CREATE TABLE IF NOT EXISTS `JGW`.`BOARD` (
  `BOARD_ID_PK` INT NOT NULL AUTO_INCREMENT,
  `BOARD_NAME` VARCHAR(45) NOT NULL,
  `ROLE_ROLE_PK_WRITE_LEVEL` INT NOT NULL,
  `ROLE_ROLE_PK_READ_LEVEL` INT NOT NULL,JGWJGW
  `ROLE_ROLE_PK_COMMENT_WRITE_LEVEL` INT NOT NULL,
  `BOARD_LAYOUT` INT NOT NULL,
  PRIMARY KEY (`BOARD_ID_PK`),
  UNIQUE INDEX `BOARD_NAME_UNIQUE` (`BOARD_NAME` ASC) VISIBLE,
  INDEX `fk_BOARD_ROLE1_idx` (`ROLE_ROLE_PK_READ_LEVEL` ASC, `ROLE_ROLE_PK_WRITE_LEVEL` ASC, `ROLE_ROLE_PK_COMMENT_WRITE_LEVEL` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

ALTER TABLE BOARD
	ADD CONSTRAINT `fk_BOARD_READ_ROLE_PK`
	FOREIGN KEY (ROLE_ROLE_PK_READ_LEVEL)
	REFERENCES ROLE (ROLE_PK)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
	
ALTER TABLE BOARD
	ADD CONSTRAINT `fk_BOARD_WRITE_ROLE_PK`
	FOREIGN KEY (ROLE_ROLE_PK_WRITE_LEVEL)
	REFERENCES ROLE (ROLE_PK)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
	
ALTER TABLE BOARD
	ADD CONSTRAINT `fk_BOARD_COMMENT_ROLE_PK`
	FOREIGN KEY (ROLE_ROLE_PK_COMMENT_WRITE_LEVEL)
	REFERENCES ROLE (ROLE_PK)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS `JGW`.`POST` (
  `POST_ID_PK` INT NOT NULL AUTO_INCREMENT,
  `POST_TITLE` VARCHAR(100) NOT NULL,
  `POST_CONTENT` LONGTEXT NOT NULL,
  `POST_WRITE_TIME` DATETIME NOT NULL,
  `POST_UPDATE_TIME` DATETIME NOT NULL,
  `IMAGE_IMAGE_ID_PK` INT NULL,
  `BOARD_BOADR_ID_PK` INT NOT NULL,
  `MEMBER_MEMBER_PK` VARCHAR(25) NULL,
  PRIMARY KEY (`POST_ID_PK`),
  INDEX `fk_POST_IMAGE1_idx` (`IMAGE_IMAGE_ID_PK` ASC) VISIBLE,
  INDEX `fk_POST_BOARD1_idx` (`BOARD_BOADR_ID_PK` ASC) VISIBLE,
  INDEX `fk_POST_MEMBER1_idx` (`MEMBER_MEMBER_PK` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

CREATE TABLE IF NOT EXISTS `JGW`.`IMAGE` (
  `IMAGE_ID_PK` INT NOT NULL AUTO_INCREMENT,
  `IMAGE_NAME` VARCHAR(45) NOT NULL,
  `IMAGE_URL` VARCHAR(45) NOT NULL,
  `POST_POST_ID_PK` INT NOT NULL,
  `MEMBER_MEMBER_PK` VARCHAR(30) NULL,
  PRIMARY KEY (`IMAGE_ID_PK`),
  INDEX `fk_IMAGE_POST_idx` (`POST_POST_ID_PK` ASC) VISIBLE,
  INDEX `fk_IMAGE_MEMBER_idx` (`MEMBER_MEMBER_PK` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

ALTER TABLE POST
	ADD CONSTRAINT `fk_POST_IMAGE1`
   FOREIGN KEY (`IMAGE_IMAGE_ID_PK`)
   REFERENCES `JGW`.`IMAGE` (`IMAGE_ID_PK`)
   ON DELETE SET NULL
   ON UPDATE CASCADE;

ALTER TABLE POST
	ADD CONSTRAINT `fk_POST_BOARD1`
   FOREIGN KEY (`BOARD_BOADR_ID_PK`)
   REFERENCES `JGW`.`BOARD` (`BOARD_ID_PK`)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

ALTER TABLE POST
	ADD CONSTRAINT `fk_POST_MEMBER1`
   FOREIGN KEY (`MEMBER_MEMBER_PK`)
   REFERENCES `JGW`.`MEMBER` (`MEMBER_PK`)
   ON DELETE SET NULL
   ON UPDATE CASCADE;
   
ALTER TABLE IMAGE
	ADD CONSTRAINT `fk_IMAGE_POST`
   FOREIGN KEY (`POST_POST_ID_PK`)
   REFERENCES `JGW`.`POST` (`POST_ID_PK`)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

ALTER TABLE IMAGE
	ADD CONSTRAINT `fk_IMAGE_MEMBER`
   FOREIGN KEY (`MEMBER_MEMBER_PK`)
   REFERENCES `JGW`.`MEMBER` (`MEMBER_PK`)
   ON DELETE SET NULL
   ON UPDATE CASCADE;

CREATE TABLE IF NOT EXISTS `JGW`.`COMMENT` (
  `COMMENT_ID` INT NOT NULL AUTO_INCREMENT,
  `COMMENT_REF_ID` INT NOT NULL,
  `COMMENT_DEPTH` INT NOT NULL,
  `COMMENT_CONTENT` MEDIUMTEXT NOT NULL,
  `COMMENT_WRITE_TIME` DATETIME NOT NULL,
  `COMMENT_UPDATE_TIME` DATETIME NOT NULL,
  `COMMENT_DELETE` ENUM('N', 'Y') NOT NULL DEFAULT 'N',
  `POST_POST_ID_PK` INT NOT NULL,
  `MEMBER_MEMBER_PK` VARCHAR(45) NULL,
  `COMMENT_COMMENT_ID_REF` INT NULL,
  PRIMARY KEY (`COMMENT_ID`),
  INDEX `fk_COMMENT_POST1_idx` (`POST_POST_ID_PK` ASC) VISIBLE,
  INDEX `fk_COMMENT_MEMBER1_idx` (`MEMBER_MEMBER_PK` ASC) VISIBLE,
  INDEX `fk_COMMENT_COMMENT1_idx` (`COMMENT_COMMENT_ID_REF` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = DEFAULT;

ALTER TABLE COMMENT
	ADD CONSTRAINT `fk_COMMENT_POST1`
   FOREIGN KEY (`POST_POST_ID_PK`)
   REFERENCES `JGW`.`POST` (`POST_ID_PK`)
   ON DELETE CASCADE
   ON UPDATE CASCADE;

ALTER TABLE COMMENT
	ADD CONSTRAINT `fk_COMMENT_MEMBER1`
   FOREIGN KEY (`MEMBER_MEMBER_PK`)
   REFERENCES `JGW`.`MEMBER` (`MEMBER_PK`)
   ON DELETE SET NULL
   ON UPDATE CASCADE;

ALTER TABLE COMMENT
	ADD CONSTRAINT `fk_COMMENT_COMMENT1`
   FOREIGN KEY (`COMMENT_COMMENT_ID_REF`)
   REFERENCES `JGW`.`COMMENT` (`COMMENT_ID`)
   ON DELETE CASCADE
   ON UPDATE CASCADE;
